awslabs/amazon-bedrock-agentcore-samples

README.md
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> fix: update readme.

01-tutorials/01-AgentCore-runtime/01-hosting-agent/README.md, 01-tutorials/03-AgentCore-identity/03-Inbound Auth example/requirements.txt, 01-tutorials/03-AgentCore-identity/04-Outbound Auth example/requirements.txt, 01-tutorials/04-AgentCore-memory/01-short-term-memory/01-single-agent/with-langgraph-agent/personal-fitness-coach.ipynb, 01-tutorials/04-AgentCore-memory/01-short-term-memory/01-single-agent/with-strands-agent/personal-agent.ipynb, 01-tutorials/04-AgentCore-memory/01-short-term-memory/01-single-agent/with-strands-agent/requirements.txt, 01-tutorials/04-AgentCore-memory/01-short-term-memory/02-multi-agent/with-strands-agent/requirements.txt, 01-tutorials/04-AgentCore-memory/01-short-term-memory/02-multi-agent/with-strands-agent/travel-planning-agent.ipynb, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-hooks/customer-support/requirements.txt, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-hooks/simple-math-assistant/math-assistant.ipynb, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-hooks/simple-math-assistant/requirements.txt, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-memory-tool/culinary-assistant.ipynb, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-memory-tool/requirements.txt, 01-tutorials/04-AgentCore-memory/02-long-term-memory/02-multi-agent/with-strands-agent/requirements.txt, 01-tutorials/requirements.txt, 02-use-cases/05-healthcare-appointment-agent/requirements.txt
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> chores: Minor fixes

01-tutorials/03-AgentCore-identity/03-Inbound Auth example/inbound_auth_runtime_with_strands_and_bedrock_models.ipynb, 01-tutorials/03-AgentCore-identity/03-Inbound Auth example/setup_cognito_user_pool.sh
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> Identity0722

01-tutorials/04-AgentCore-memory/01-short-term-memory/02-multi-agent/with-strands-agent/travel-planning-agent.ipynb, 01-tutorials/04-AgentCore-memory/02-long-term-memory/01-single-agent/using-strands-agent-memory-tool/culinary-assistant.ipynb, 02-use-cases/customer-support-assistant/scripts/agentcore_memory.py, 02-use-cases/video-games-sales-assistant/agentcore-strands-data-analyst-assistant/resources/memory_manager.py
'id' is the correct key for memory in CreateMemory and ListMemories
=> fix(memory): use id instead of memoryid

01-tutorials/01-AgentCore-runtime/01-hosting-agent/01-strands-with-bedrock-model/runtime_with_strands_and_bedrock_models.ipynb, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/README.md
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> modified readme with correction wording

README.md
<hr/>
```
Updated README.md to reflect the correct license information, changing from MIT License to Apache License 2.0 to match the actual LICENSE file in the repository. This ensures consistency between the documentation and the actual license governing the project.
```
<hr/>
**Reason:** No specific issue ticket was created for this documentation correction.
<hr/>
<hr/>
<hr/>
- `README.md` - Updated license section to reflect Apache License 2.0
The LICENSE file in the repository root confirms this project uses Apache …
=> fix LICENSE for README

03-integrations/agentic-frameworks/strands-agents/README.md, 03-integrations/agentic-frameworks/strands-agents/strands_openai_identity.py
- **changes to openai + strands + identity client**
- **changes to openai + strands + identity client**
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> fixing openai auth example

01-tutorials/utils.py
It should be 
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
rather than:
"ecr: BatchGetImage",
"ecr: GetDownloadUrlForLayer"
There is an extrac space
<hr/>
```
Remove the extra space within "ecr: BatchGetImage" and "ecr: BatchGetImage" 
```
<hr/>
* [] Issue # (if applicable)
<hr/>
<hr/>
<hr/>
=> Update utils.py to fix syntax error caused by space

02-use-cases/healthcare-appointment-agent/requirements.txt
Updated MCP Client to version >=1.10.0 as lower versions can lead to uncaught ClosedResourceError on the server side
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> Updated MCP Client to version >=1.10.0 as lower versions can lead to uncaught ClosedResourceError on the server side

01-tutorials/06-AgentCore-observability/02-Agent-not-hosted-on-runtime/Strands/Strands_Observability.ipynb
<hr/>
```
```
notebook referencing "duckduckgo_search" while the requirements is using "ddgs". Updating the code to use "ddgs"
<hr/>
<hr/>
<hr/>
<hr/>
=> Updating the code to use "ddgs"

02-use-cases/AWS-operations-agent/README.md, 02-use-cases/AWS-operations-agent/config/static-config.yaml, 02-use-cases/AWS-operations-agent/okta-auth/OKTA-OPENID-PKCE-SETUP.md, 02-use-cases/AWS-operations-agent/okta-auth/nginx/okta-local.conf
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> Updated Readme.md

01-tutorials/02-AgentCore-gateway/01-transform-lambda-into-mcp-tools/01-gateway-target-lambda.ipynb, 01-tutorials/02-AgentCore-gateway/02-transform-apis-into-mcp-tools/01-transform-openapi-into-mcp-tools/01-openapis-into-mcp-api-key.ipynb, 01-tutorials/02-AgentCore-gateway/02-transform-apis-into-mcp-tools/01-transform-openapi-into-mcp-tools/02-openapis-into-mcp-oauth-enterprise-apis.ipynb, 01-tutorials/02-AgentCore-gateway/02-transform-apis-into-mcp-tools/02-transform-smithyapis-into-mcp-tools/01-s3-smithy-into-mcp-iam.ipynb
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> fix: minor changes

01-tutorials/03-AgentCore-identity/05-Outbound_Auth_3lo/runtime_with_strands_and_egress_3lo.ipynb
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> Updated additional permissions

01-tutorials/07-AgentCore-E2E/lab-02-agentcore-memory.ipynb, 01-tutorials/07-AgentCore-E2E/lab-04-agentcore-runtime.ipynb, 01-tutorials/07-AgentCore-E2E/lab_helpers/utils.py
<hr/>
```
```
<hr/>
<hr/>
<hr/>
<hr/>
=> Tutorial E2E: updates

01-tutorials/05-AgentCore-tools/02-Agent-Core-browser-tool/interactive_tools/browser_viewer.py, 01-tutorials/05-AgentCore-tools/02-Agent-Core-browser-tool/interactive_tools/live_view_sessionreplay/browser_viewer_replay.py, 01-tutorials/05-AgentCore-tools/02-Agent-Core-browser-tool/interactive_tools/live_view_sessionreplay/session_replay_viewer.py
- Fixed socket binding to use 127.0.0.1 instead of all interfaces
- Improved error handling to prevent stack trace exposure
- Additional security improvements
=> Fix security issues identified by CodeQL scan

01-tutorials/01-AgentCore-runtime/01-hosting-agent/01-strands-with-bedrock-model/runtime_with_strands_and_bedrock_models.ipynb
=> Fix: avoid duplicate final output in 01-runtime_with_strands_and_bedrock_models strands_claude.py

.github/workflows/ash-full-repository-scan.yml
```
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the [project license](https://github.com/awslabs/amazon-bedrock-agentcore-samples/blob/main/LICENSE).
=> Remove SARIF reporting from ASH workflow

01-tutorials/03-AgentCore-identity/05-Outbound_Auth_3lo/runtime_with_strands_and_egress_3lo.ipynb, 01-tutorials/07-AgentCore-E2E/requirements.txt, CONTRIBUTORS.md
```
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the [project license](https://github.com/awslabs/amazon-bedrock-agentcore-samples/blob/main/LICENSE).
=> PR to fix typo add missing package and added name in contributors.

02-use-cases/text-to-python-ide/frontend/index.html, 02-use-cases/text-to-python-ide/frontend/package-lock.json, 02-use-cases/text-to-python-ide/frontend/package.json, 02-use-cases/text-to-python-ide/frontend/src/App.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/CodeDisplay.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/CodeEditor.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/CsvUploadModal.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/ExecutionResults.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/ExecutionTimer.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/ImageDisplay.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/InteractiveExecutionModal.jsx, 02-use-cases/text-to-python-ide/frontend/src/components/SessionHistory.jsx, 02-use-cases/text-to-python-ide/frontend/src/index.jsx, 02-use-cases/text-to-python-ide/frontend/src/services/api.js, 02-use-cases/text-to-python-ide/frontend/vite.config.js
https://github.com/awslabs/amazon-bedrock-agentcore-samples/security/dependabot/27
https://github.com/awslabs/amazon-bedrock-agentcore-samples/security/dependabot/30
https://github.com/awslabs/amazon-bedrock-agentcore-samples/security/dependabot/29
https://github.com/awslabs/amazon-bedrock-agentcore-samples/security/dependabot/28
```
This PR is to address the above listed issues. It addresses security vulnerabilities in the react components that …
```
=> updated to remove vulnerable react components

01-tutorials/01-AgentCore-runtime/01-hosting-agent/01-strands-with-bedrock-model/runtime_with_strands_and_bedrock_models.ipynb, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/02-langgraph-with-bedrock-model/runtime_with_langgraph_and_bedrock_models.ipynb, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/03-strands-with-openai-model/runtime_with_strands_and_openai_models.ipynb, 01-tutorials/01-AgentCore-runtime/03-advanced-concepts/02-understanding-runtime-context/understanding_runtime_context.ipynb, 01-tutorials/01-AgentCore-runtime/03-advanced-concepts/03-handling-large-payloads/handling_large_payloads.ipynb, 01-tutorials/03-AgentCore-identity/04-Outbound Auth example/runtime_with_strands_and_openai_models.ipynb, 01-tutorials/04-AgentCore-memory/03-advanced-patterns/02-memory-runtime-integration/runtime_memory_integration.ipynb, 01-tutorials/06-AgentCore-observability/01-Agentcore-runtime-hosted/runtime_with_strands_and_bedrock_models.ipynb, CONTRIBUTORS.md
**Issue number**: #343
Fixes #343 
```
Changes to tutorial notebooks across multiple AgentCore components to remove manual response decoding and JSON parsing, because bedrock-agentcore-starter-toolkit v0.1.10+ now automatically handles these operations in the Runtime class.
This fixes the 'str' object has no attribute 'decode' error that occurs when running tutorial notebooks with the latest starter toolkit version.
```
> Please share what the user experience looks …
=> Fix tutorial notebooks compatibility with starter toolkit v0.1.10+

03-integrations/agentic-frameworks/adk/README.md
```
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the [project license](https://github.com/awslabs/amazon-bedrock-agentcore-samples/blob/main/LICENSE).
=> Update README.md (fixing ADK readme)

01-tutorials/07-AgentCore-E2E/lab-01-create-an-agent.ipynb, 01-tutorials/07-AgentCore-E2E/lab-02-agentcore-memory.ipynb, 01-tutorials/07-AgentCore-E2E/scripts/prereq.ps1, 01-tutorials/07-AgentCore-E2E/scripts/prereq.sh
```
```
prereq.sh fix for failing cognito setup and moving the instructions for selfpaced prereqs from lab-2 to lab-1 (as the lab-1 needs the prereqs)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Self paced lab updates

01-tutorials/01-AgentCore-runtime/01-hosting-agent/01-strands-with-bedrock-model/requirements.txt, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/02-langgraph-with-bedrock-model/requirements.txt, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/03-strands-with-openai-model/requirements.txt, 01-tutorials/01-AgentCore-runtime/01-hosting-agent/04-crewai-with-bedrock-model/research_crew/requirements.txt, 01-tutorials/01-AgentCore-runtime/02-hosting-MCP-server/requirements.txt, 01-tutorials/01-AgentCore-runtime/03-advanced-concepts/01-streaming-agent-response/requirements.txt, 01-tutorials/01-AgentCore-runtime/03-advanced-concepts/02-understanding-runtime-context/requirements.txt, 01-tutorials/01-AgentCore-runtime/03-advanced-concepts/03-handling-large-payloads/requirements.txt, 01-tutorials/07-AgentCore-E2E/requirements.txt
```
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the [project license](https://github.com/awslabs/amazon-bedrock-agentcore-samples/blob/main/LICENSE).
=> fix: agentcore sdk version fix
